### ISSUE TITLE
Creates infinite subprocesses

### ISSUE THREAD

**Issue by maxabrahamsson** [vrublack/GY-85#1]
Hi,

I think you do not need the While True loop for the creation of subprocesses. That causes infinite amount of processes to start. Am I wrong?
https://github.com/vrublack/GY-85/blob/7707eb38fdb4f499fb65c6790a47d3b27f41f24c/main.py#L28

It caused weird errors on my Macbook :
" fork: Resource temporarily unavailable "

After I removed the While True and just start 1 subprocess. The error was gone.

**Comment by vrublack** [comment]
The sensor_reader.start_reading() is blocking and keeps reading from the sensors (unless the sensors are unavailable which might have happened in your case) so the loop usually only executes once. I'm not sure why the loop existed in the first place though so it can probably be removed.
